// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/authz/v1/api.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/aegis-run/aegis/proto/aegis/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Decision represents the authorization outcome.
type AuthorizeResponse_Decision int32

const (
	AuthorizeResponse_DECISION_UNSPECIFIED AuthorizeResponse_Decision = 0
	AuthorizeResponse_DECISION_ALLOWED     AuthorizeResponse_Decision = 1
	AuthorizeResponse_DECISION_DENIED      AuthorizeResponse_Decision = 2
)

// Enum value maps for AuthorizeResponse_Decision.
var (
	AuthorizeResponse_Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "DECISION_ALLOWED",
		2: "DECISION_DENIED",
	}
	AuthorizeResponse_Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"DECISION_ALLOWED":     1,
		"DECISION_DENIED":      2,
	}
)

func (x AuthorizeResponse_Decision) Enum() *AuthorizeResponse_Decision {
	p := new(AuthorizeResponse_Decision)
	*p = x
	return p
}

func (x AuthorizeResponse_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizeResponse_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_aegis_authz_v1_api_proto_enumTypes[0].Descriptor()
}

func (AuthorizeResponse_Decision) Type() protoreflect.EnumType {
	return &file_aegis_authz_v1_api_proto_enumTypes[0]
}

func (x AuthorizeResponse_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizeResponse_Decision.Descriptor instead.
func (AuthorizeResponse_Decision) EnumDescriptor() ([]byte, []int) {
	return file_aegis_authz_v1_api_proto_rawDescGZIP(), []int{1, 0}
}

// Request payload for Authz.Authorize.
// Focuses strictly on the core logical access check question.
type AuthorizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource instance being accessed, e.g., document("doc_1").
	Resource *v1.Instance `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The computed permission or relation to check, e.g., "viewer".
	Permission string `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	// The atomic actor seeking access, e.g., user("alice").
	// Per the Aegis taxonomy, an Actor must always be an atomic Instance.
	Actor *v1.Instance `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// Optional consistency requirements under which the check should be evaluated.
	Consistency   *v1.Consistency `protobuf:"bytes,4,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_aegis_authz_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_authz_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_aegis_authz_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetResource() *v1.Instance {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AuthorizeRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *AuthorizeRequest) GetActor() *v1.Instance {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AuthorizeRequest) GetConsistency() *v1.Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

// Response payload for Authz.Authorize.
type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The authorization decision.
	Decision AuthorizeResponse_Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=aegis.authz.v1.AuthorizeResponse_Decision" json:"decision,omitempty"`
	// Consistency token representing the datastore revision at the time
	// of evaluation. Pass to subsequent reads to enforce causal consistency.
	CheckedAt     *v1.ConsistencyToken `protobuf:"bytes,2,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_aegis_authz_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_authz_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_aegis_authz_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetDecision() AuthorizeResponse_Decision {
	if x != nil {
		return x.Decision
	}
	return AuthorizeResponse_DECISION_UNSPECIFIED
}

func (x *AuthorizeResponse) GetCheckedAt() *v1.ConsistencyToken {
	if x != nil {
		return x.CheckedAt
	}
	return nil
}

var File_aegis_authz_v1_api_proto protoreflect.FileDescriptor

const file_aegis_authz_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x18aegis/authz/v1/api.proto\x12\x0eaegis.authz.v1\x1a\x14aegis/v1/authz.proto\x1a\x1aaegis/v1/consistency.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\x83\x02\n" +
	"\x10AuthorizeRequest\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x12.aegis.v1.InstanceB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12L\n" +
	"\n" +
	"permission\x18\x02 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\n" +
	"permission\x120\n" +
	"\x05actor\x18\x03 \x01(\v2\x12.aegis.v1.InstanceB\x06\xbaH\x03\xc8\x01\x01R\x05actor\x127\n" +
	"\vconsistency\x18\x04 \x01(\v2\x15.aegis.v1.ConsistencyR\vconsistency\"\xe7\x01\n" +
	"\x11AuthorizeResponse\x12F\n" +
	"\bdecision\x18\x01 \x01(\x0e2*.aegis.authz.v1.AuthorizeResponse.DecisionR\bdecision\x129\n" +
	"\n" +
	"checked_at\x18\x02 \x01(\v2\x1a.aegis.v1.ConsistencyTokenR\tcheckedAt\"O\n" +
	"\bDecision\x12\x18\n" +
	"\x14DECISION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DECISION_ALLOWED\x10\x01\x12\x13\n" +
	"\x0fDECISION_DENIED\x10\x022y\n" +
	"\x05Authz\x12p\n" +
	"\tAuthorize\x12 .aegis.authz.v1.AuthorizeRequest\x1a!.aegis.authz.v1.AuthorizeResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/authz/authorizeB1Z/github.com/aegis-run/aegis/proto/aegis/authz/v1b\x06proto3"

var (
	file_aegis_authz_v1_api_proto_rawDescOnce sync.Once
	file_aegis_authz_v1_api_proto_rawDescData []byte
)

func file_aegis_authz_v1_api_proto_rawDescGZIP() []byte {
	file_aegis_authz_v1_api_proto_rawDescOnce.Do(func() {
		file_aegis_authz_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_authz_v1_api_proto_rawDesc), len(file_aegis_authz_v1_api_proto_rawDesc)))
	})
	return file_aegis_authz_v1_api_proto_rawDescData
}

var file_aegis_authz_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aegis_authz_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aegis_authz_v1_api_proto_goTypes = []any{
	(AuthorizeResponse_Decision)(0), // 0: aegis.authz.v1.AuthorizeResponse.Decision
	(*AuthorizeRequest)(nil),        // 1: aegis.authz.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil),       // 2: aegis.authz.v1.AuthorizeResponse
	(*v1.Instance)(nil),             // 3: aegis.v1.Instance
	(*v1.Consistency)(nil),          // 4: aegis.v1.Consistency
	(*v1.ConsistencyToken)(nil),     // 5: aegis.v1.ConsistencyToken
}
var file_aegis_authz_v1_api_proto_depIdxs = []int32{
	3, // 0: aegis.authz.v1.AuthorizeRequest.resource:type_name -> aegis.v1.Instance
	3, // 1: aegis.authz.v1.AuthorizeRequest.actor:type_name -> aegis.v1.Instance
	4, // 2: aegis.authz.v1.AuthorizeRequest.consistency:type_name -> aegis.v1.Consistency
	0, // 3: aegis.authz.v1.AuthorizeResponse.decision:type_name -> aegis.authz.v1.AuthorizeResponse.Decision
	5, // 4: aegis.authz.v1.AuthorizeResponse.checked_at:type_name -> aegis.v1.ConsistencyToken
	1, // 5: aegis.authz.v1.Authz.Authorize:input_type -> aegis.authz.v1.AuthorizeRequest
	2, // 6: aegis.authz.v1.Authz.Authorize:output_type -> aegis.authz.v1.AuthorizeResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_aegis_authz_v1_api_proto_init() }
func file_aegis_authz_v1_api_proto_init() {
	if File_aegis_authz_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_authz_v1_api_proto_rawDesc), len(file_aegis_authz_v1_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_authz_v1_api_proto_goTypes,
		DependencyIndexes: file_aegis_authz_v1_api_proto_depIdxs,
		EnumInfos:         file_aegis_authz_v1_api_proto_enumTypes,
		MessageInfos:      file_aegis_authz_v1_api_proto_msgTypes,
	}.Build()
	File_aegis_authz_v1_api_proto = out.File
	file_aegis_authz_v1_api_proto_goTypes = nil
	file_aegis_authz_v1_api_proto_depIdxs = nil
}
