// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/data/v1/api.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/aegis-run/aegis/proto/aegis/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TupleMutation_Operation int32

const (
	TupleMutation_OPERATION_UNSPECIFIED TupleMutation_Operation = 0
	TupleMutation_OPERATION_WRITE       TupleMutation_Operation = 1
	TupleMutation_OPERATION_DELETE      TupleMutation_Operation = 2
)

// Enum value maps for TupleMutation_Operation.
var (
	TupleMutation_Operation_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_WRITE",
		2: "OPERATION_DELETE",
	}
	TupleMutation_Operation_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_WRITE":       1,
		"OPERATION_DELETE":      2,
	}
)

func (x TupleMutation_Operation) Enum() *TupleMutation_Operation {
	p := new(TupleMutation_Operation)
	*p = x
	return p
}

func (x TupleMutation_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TupleMutation_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_aegis_data_v1_api_proto_enumTypes[0].Descriptor()
}

func (TupleMutation_Operation) Type() protoreflect.EnumType {
	return &file_aegis_data_v1_api_proto_enumTypes[0]
}

func (x TupleMutation_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TupleMutation_Operation.Descriptor instead.
func (TupleMutation_Operation) EnumDescriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{0, 0}
}

// Represents a single mutation operation to apply to a relationship tuple.
type TupleMutation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operation to perform (WRITE or DELETE).
	Operation TupleMutation_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=aegis.data.v1.TupleMutation_Operation" json:"operation,omitempty"`
	// The relationship tuple to mutate.
	Tuple         *v1.Tuple `protobuf:"bytes,2,opt,name=tuple,proto3" json:"tuple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleMutation) Reset() {
	*x = TupleMutation{}
	mi := &file_aegis_data_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleMutation) ProtoMessage() {}

func (x *TupleMutation) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_data_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleMutation.ProtoReflect.Descriptor instead.
func (*TupleMutation) Descriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *TupleMutation) GetOperation() TupleMutation_Operation {
	if x != nil {
		return x.Operation
	}
	return TupleMutation_OPERATION_UNSPECIFIED
}

func (x *TupleMutation) GetTuple() *v1.Tuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

// A filter representing a query pattern to find stored relationship tuples.
// Restricts queries at the type level to enforce either forward or reverse queries.
type TupleFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target query scope (must choose resource or subject).
	//
	// Types that are valid to be assigned to QueryTarget:
	//
	//	*TupleFilter_Resource
	//	*TupleFilter_Subject
	QueryTarget isTupleFilter_QueryTarget `protobuf_oneof:"query_target"`
	// Optional relation name filter.
	Relation      string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleFilter) Reset() {
	*x = TupleFilter{}
	mi := &file_aegis_data_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleFilter) ProtoMessage() {}

func (x *TupleFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_data_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleFilter.ProtoReflect.Descriptor instead.
func (*TupleFilter) Descriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *TupleFilter) GetQueryTarget() isTupleFilter_QueryTarget {
	if x != nil {
		return x.QueryTarget
	}
	return nil
}

func (x *TupleFilter) GetResource() *TupleFilter_InstanceFilter {
	if x != nil {
		if x, ok := x.QueryTarget.(*TupleFilter_Resource); ok {
			return x.Resource
		}
	}
	return nil
}

func (x *TupleFilter) GetSubject() *TupleFilter_SubjectFilter {
	if x != nil {
		if x, ok := x.QueryTarget.(*TupleFilter_Subject); ok {
			return x.Subject
		}
	}
	return nil
}

func (x *TupleFilter) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type isTupleFilter_QueryTarget interface {
	isTupleFilter_QueryTarget()
}

type TupleFilter_Resource struct {
	// Filter starting from resource properties.
	Resource *TupleFilter_InstanceFilter `protobuf:"bytes,1,opt,name=resource,proto3,oneof"`
}

type TupleFilter_Subject struct {
	// Filter starting from subject properties.
	Subject *TupleFilter_SubjectFilter `protobuf:"bytes,3,opt,name=subject,proto3,oneof"`
}

func (*TupleFilter_Resource) isTupleFilter_QueryTarget() {}

func (*TupleFilter_Subject) isTupleFilter_QueryTarget() {}

// Request payload for Data.Mutate.
type MutateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence of mutations to execute atomically in a single transaction.
	Mutations     []*TupleMutation `protobuf:"bytes,1,rep,name=mutations,proto3" json:"mutations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRequest) Reset() {
	*x = MutateRequest{}
	mi := &file_aegis_data_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRequest) ProtoMessage() {}

func (x *MutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_data_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRequest.ProtoReflect.Descriptor instead.
func (*MutateRequest) Descriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *MutateRequest) GetMutations() []*TupleMutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

// Response payload for Data.Mutate.
type MutateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The database revision (consistency token) at which the transaction committed.
	// Pass to subsequent reads to enforce causal consistency.
	ConsistencyToken *v1.ConsistencyToken `protobuf:"bytes,1,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MutateResponse) Reset() {
	*x = MutateResponse{}
	mi := &file_aegis_data_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateResponse) ProtoMessage() {}

func (x *MutateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_data_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateResponse.ProtoReflect.Descriptor instead.
func (*MutateResponse) Descriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *MutateResponse) GetConsistencyToken() *v1.ConsistencyToken {
	if x != nil {
		return x.ConsistencyToken
	}
	return nil
}

// Request payload for Data.Query.
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The query filter starting from resource properties or subject properties.
	Filter *TupleFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// Optional consistency requirements under which the query should be executed.
	Consistency *v1.Consistency `protobuf:"bytes,2,opt,name=consistency,proto3" json:"consistency,omitempty"`
	// Pagination request parameters.
	Page          *v1.Pagination `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_aegis_data_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_data_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *QueryRequest) GetFilter() *TupleFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryRequest) GetConsistency() *v1.Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *QueryRequest) GetPage() *v1.Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

// Response payload for Data.Query.
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of matching relationship tuples nested under data.
	Data []*v1.Tuple `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Pagination response parameters.
	Page *v1.Page `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	// The database revision at which the query was executed.
	// Pass to subsequent reads to enforce causal consistency.
	ConsistencyToken *v1.ConsistencyToken `protobuf:"bytes,3,opt,name=consistency_token,json=consistencyToken,proto3" json:"consistency_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_aegis_data_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_data_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetData() []*v1.Tuple {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueryResponse) GetPage() *v1.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *QueryResponse) GetConsistencyToken() *v1.ConsistencyToken {
	if x != nil {
		return x.ConsistencyToken
	}
	return nil
}

// Filters resource-scoped properties (forward lookup starting from resource).
type TupleFilter_InstanceFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of resource to filter, e.g., "document".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Optional identifier of the resource instance.
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleFilter_InstanceFilter) Reset() {
	*x = TupleFilter_InstanceFilter{}
	mi := &file_aegis_data_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleFilter_InstanceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleFilter_InstanceFilter) ProtoMessage() {}

func (x *TupleFilter_InstanceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_data_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleFilter_InstanceFilter.ProtoReflect.Descriptor instead.
func (*TupleFilter_InstanceFilter) Descriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TupleFilter_InstanceFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TupleFilter_InstanceFilter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Filters subject-scoped properties (reverse lookup starting from subject).
type TupleFilter_SubjectFilter struct {
	state    protoimpl.MessageState      `protogen:"open.v1"`
	Instance *TupleFilter_InstanceFilter `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Optional permission or relation on the subject instance.
	Permission    string `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TupleFilter_SubjectFilter) Reset() {
	*x = TupleFilter_SubjectFilter{}
	mi := &file_aegis_data_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleFilter_SubjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleFilter_SubjectFilter) ProtoMessage() {}

func (x *TupleFilter_SubjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_data_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleFilter_SubjectFilter.ProtoReflect.Descriptor instead.
func (*TupleFilter_SubjectFilter) Descriptor() ([]byte, []int) {
	return file_aegis_data_v1_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *TupleFilter_SubjectFilter) GetInstance() *TupleFilter_InstanceFilter {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *TupleFilter_SubjectFilter) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

var File_aegis_data_v1_api_proto protoreflect.FileDescriptor

const file_aegis_data_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x17aegis/data/v1/api.proto\x12\raegis.data.v1\x1a\x14aegis/v1/authz.proto\x1a\x1aaegis/v1/consistency.proto\x1a\x19aegis/v1/pagination.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"\xe1\x01\n" +
	"\rTupleMutation\x12N\n" +
	"\toperation\x18\x01 \x01(\x0e2&.aegis.data.v1.TupleMutation.OperationB\b\xbaH\x05\x82\x01\x02\x10\x01R\toperation\x12-\n" +
	"\x05tuple\x18\x02 \x01(\v2\x0f.aegis.v1.TupleB\x06\xbaH\x03\xc8\x01\x01R\x05tuple\"Q\n" +
	"\tOperation\x12\x19\n" +
	"\x15OPERATION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOPERATION_WRITE\x10\x01\x12\x14\n" +
	"\x10OPERATION_DELETE\x10\x02\"\x94\x04\n" +
	"\vTupleFilter\x12G\n" +
	"\bresource\x18\x01 \x01(\v2).aegis.data.v1.TupleFilter.InstanceFilterH\x00R\bresource\x12D\n" +
	"\asubject\x18\x03 \x01(\v2(.aegis.data.v1.TupleFilter.SubjectFilterH\x00R\asubject\x12I\n" +
	"\brelation\x18\x02 \x01(\tB-\xbaH*r((@2$^$|^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\brelation\x1al\n" +
	"\x0eInstanceFilter\x12@\n" +
	"\x04type\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\x04type\x12\x18\n" +
	"\x02id\x18\x02 \x01(\tB\b\xbaH\x05r\x03(\x80\x01R\x02id\x1a\xa5\x01\n" +
	"\rSubjectFilter\x12E\n" +
	"\binstance\x18\x01 \x01(\v2).aegis.data.v1.TupleFilter.InstanceFilterR\binstance\x12M\n" +
	"\n" +
	"permission\x18\x02 \x01(\tB-\xbaH*r((@2$^$|^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\n" +
	"permissionB\x15\n" +
	"\fquery_target\x12\x05\xbaH\x02\b\x01\"X\n" +
	"\rMutateRequest\x12G\n" +
	"\tmutations\x18\x01 \x03(\v2\x1c.aegis.data.v1.TupleMutationB\v\xbaH\b\x92\x01\x05\b\x01\x10\xe8\aR\tmutations\"Y\n" +
	"\x0eMutateResponse\x12G\n" +
	"\x11consistency_token\x18\x01 \x01(\v2\x1a.aegis.v1.ConsistencyTokenR\x10consistencyToken\"\xad\x01\n" +
	"\fQueryRequest\x12:\n" +
	"\x06filter\x18\x01 \x01(\v2\x1a.aegis.data.v1.TupleFilterB\x06\xbaH\x03\xc8\x01\x01R\x06filter\x127\n" +
	"\vconsistency\x18\x02 \x01(\v2\x15.aegis.v1.ConsistencyR\vconsistency\x12(\n" +
	"\x04page\x18\x03 \x01(\v2\x14.aegis.v1.PaginationR\x04page\"\xa1\x01\n" +
	"\rQueryResponse\x12#\n" +
	"\x04data\x18\x01 \x03(\v2\x0f.aegis.v1.TupleR\x04data\x12\"\n" +
	"\x04page\x18\x02 \x01(\v2\x0e.aegis.v1.PageR\x04page\x12G\n" +
	"\x11consistency_token\x18\x03 \x01(\v2\x1a.aegis.v1.ConsistencyTokenR\x10consistencyToken2\xc8\x01\n" +
	"\x04Data\x12a\n" +
	"\x06Mutate\x12\x1c.aegis.data.v1.MutateRequest\x1a\x1d.aegis.data.v1.MutateResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/data/mutate\x12]\n" +
	"\x05Query\x12\x1b.aegis.data.v1.QueryRequest\x1a\x1c.aegis.data.v1.QueryResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/data/queryB0Z.github.com/aegis-run/aegis/proto/aegis/data/v1b\x06proto3"

var (
	file_aegis_data_v1_api_proto_rawDescOnce sync.Once
	file_aegis_data_v1_api_proto_rawDescData []byte
)

func file_aegis_data_v1_api_proto_rawDescGZIP() []byte {
	file_aegis_data_v1_api_proto_rawDescOnce.Do(func() {
		file_aegis_data_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_data_v1_api_proto_rawDesc), len(file_aegis_data_v1_api_proto_rawDesc)))
	})
	return file_aegis_data_v1_api_proto_rawDescData
}

var file_aegis_data_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aegis_data_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_aegis_data_v1_api_proto_goTypes = []any{
	(TupleMutation_Operation)(0),       // 0: aegis.data.v1.TupleMutation.Operation
	(*TupleMutation)(nil),              // 1: aegis.data.v1.TupleMutation
	(*TupleFilter)(nil),                // 2: aegis.data.v1.TupleFilter
	(*MutateRequest)(nil),              // 3: aegis.data.v1.MutateRequest
	(*MutateResponse)(nil),             // 4: aegis.data.v1.MutateResponse
	(*QueryRequest)(nil),               // 5: aegis.data.v1.QueryRequest
	(*QueryResponse)(nil),              // 6: aegis.data.v1.QueryResponse
	(*TupleFilter_InstanceFilter)(nil), // 7: aegis.data.v1.TupleFilter.InstanceFilter
	(*TupleFilter_SubjectFilter)(nil),  // 8: aegis.data.v1.TupleFilter.SubjectFilter
	(*v1.Tuple)(nil),                   // 9: aegis.v1.Tuple
	(*v1.ConsistencyToken)(nil),        // 10: aegis.v1.ConsistencyToken
	(*v1.Consistency)(nil),             // 11: aegis.v1.Consistency
	(*v1.Pagination)(nil),              // 12: aegis.v1.Pagination
	(*v1.Page)(nil),                    // 13: aegis.v1.Page
}
var file_aegis_data_v1_api_proto_depIdxs = []int32{
	0,  // 0: aegis.data.v1.TupleMutation.operation:type_name -> aegis.data.v1.TupleMutation.Operation
	9,  // 1: aegis.data.v1.TupleMutation.tuple:type_name -> aegis.v1.Tuple
	7,  // 2: aegis.data.v1.TupleFilter.resource:type_name -> aegis.data.v1.TupleFilter.InstanceFilter
	8,  // 3: aegis.data.v1.TupleFilter.subject:type_name -> aegis.data.v1.TupleFilter.SubjectFilter
	1,  // 4: aegis.data.v1.MutateRequest.mutations:type_name -> aegis.data.v1.TupleMutation
	10, // 5: aegis.data.v1.MutateResponse.consistency_token:type_name -> aegis.v1.ConsistencyToken
	2,  // 6: aegis.data.v1.QueryRequest.filter:type_name -> aegis.data.v1.TupleFilter
	11, // 7: aegis.data.v1.QueryRequest.consistency:type_name -> aegis.v1.Consistency
	12, // 8: aegis.data.v1.QueryRequest.page:type_name -> aegis.v1.Pagination
	9,  // 9: aegis.data.v1.QueryResponse.data:type_name -> aegis.v1.Tuple
	13, // 10: aegis.data.v1.QueryResponse.page:type_name -> aegis.v1.Page
	10, // 11: aegis.data.v1.QueryResponse.consistency_token:type_name -> aegis.v1.ConsistencyToken
	7,  // 12: aegis.data.v1.TupleFilter.SubjectFilter.instance:type_name -> aegis.data.v1.TupleFilter.InstanceFilter
	3,  // 13: aegis.data.v1.Data.Mutate:input_type -> aegis.data.v1.MutateRequest
	5,  // 14: aegis.data.v1.Data.Query:input_type -> aegis.data.v1.QueryRequest
	4,  // 15: aegis.data.v1.Data.Mutate:output_type -> aegis.data.v1.MutateResponse
	6,  // 16: aegis.data.v1.Data.Query:output_type -> aegis.data.v1.QueryResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_aegis_data_v1_api_proto_init() }
func file_aegis_data_v1_api_proto_init() {
	if File_aegis_data_v1_api_proto != nil {
		return
	}
	file_aegis_data_v1_api_proto_msgTypes[1].OneofWrappers = []any{
		(*TupleFilter_Resource)(nil),
		(*TupleFilter_Subject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_data_v1_api_proto_rawDesc), len(file_aegis_data_v1_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_data_v1_api_proto_goTypes,
		DependencyIndexes: file_aegis_data_v1_api_proto_depIdxs,
		EnumInfos:         file_aegis_data_v1_api_proto_enumTypes,
		MessageInfos:      file_aegis_data_v1_api_proto_msgTypes,
	}.Build()
	File_aegis_data_v1_api_proto = out.File
	file_aegis_data_v1_api_proto_goTypes = nil
	file_aegis_data_v1_api_proto_depIdxs = nil
}
