// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/authz.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a concrete, typed resource or actor instance within the Aegis system.
//
// Examples in `aes` syntax:
// - A user instance: `user("alice")`
// - A document instance: `document("doc_1")`
// - A group instance: `group("engineering")`
type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the instance, e.g., "user" or "document".
	// Must match a declared TypeDefinition name in the validated schema.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The unique identifier of this specific instance, e.g., "alice" or "doc_1".
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_aegis_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *Instance) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Represents the entity being checked, queried, or granted permissions.
//
// A Subject is either a direct, concrete instance (such as a specific user) or
// a nested userset (such as the set of members belonging to a team).
//
// Examples in `aes` syntax:
// - Direct User: `user("alice")`
// - Userset (members of group eng): `group("eng")::member`
type Subject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The underlying resource or actor instance representing this subject.
	Instance *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Optional permission or relation on the referenced instance.
	// If present, this subject represents the userset of all actors who satisfy
	// this permission on the instance. If empty, represents the direct instance.
	Permission    string `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_aegis_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *Subject) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *Subject) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

// Represents an explicit relationship edge between a resource and a subject.
//
// Relationship tuples are the core "facts" persisted in the database that form
// the authorization graph.
//
// Examples in `aes` syntax:
//   - Granting user 'alice' ownership of document 'doc_1':
//     `document("doc_1").owner: user("alice");`
//   - Granting members of team 'eng' viewer access to document 'doc_1':
//     `document("doc_1").viewer: team("eng")::member;`
type Tuple struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource instance on which the relation is defined.
	Resource *Instance `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// The relation name. Must match a 'Relation' name in the resource's TypeDefinition.
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	// The subject entity being granted this relation.
	Subject       *Subject `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tuple) Reset() {
	*x = Tuple{}
	mi := &file_aegis_v1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tuple) ProtoMessage() {}

func (x *Tuple) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tuple.ProtoReflect.Descriptor instead.
func (*Tuple) Descriptor() ([]byte, []int) {
	return file_aegis_v1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *Tuple) GetResource() *Instance {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Tuple) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Tuple) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

var File_aegis_v1_authz_proto protoreflect.FileDescriptor

const file_aegis_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x14aegis/v1/authz.proto\x12\baegis.v1\x1a\x1bbuf/validate/validate.proto\"h\n" +
	"\bInstance\x12@\n" +
	"\x04type\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\x04type\x12\x1a\n" +
	"\x02id\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01(\x80\x01R\x02id\"\x90\x01\n" +
	"\aSubject\x126\n" +
	"\binstance\x18\x01 \x01(\v2\x12.aegis.v1.InstanceB\x06\xbaH\x03\xc8\x01\x01R\binstance\x12M\n" +
	"\n" +
	"permission\x18\x02 \x01(\tB-\xbaH*r((@2$^$|^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\n" +
	"permission\"\xbe\x01\n" +
	"\x05Tuple\x126\n" +
	"\bresource\x18\x01 \x01(\v2\x12.aegis.v1.InstanceB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12H\n" +
	"\brelation\x18\x02 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\brelation\x123\n" +
	"\asubject\x18\x03 \x01(\v2\x11.aegis.v1.SubjectB\x06\xbaH\x03\xc8\x01\x01R\asubjectB+Z)github.com/aegis-run/aegis/proto/aegis/v1b\x06proto3"

var (
	file_aegis_v1_authz_proto_rawDescOnce sync.Once
	file_aegis_v1_authz_proto_rawDescData []byte
)

func file_aegis_v1_authz_proto_rawDescGZIP() []byte {
	file_aegis_v1_authz_proto_rawDescOnce.Do(func() {
		file_aegis_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_authz_proto_rawDesc), len(file_aegis_v1_authz_proto_rawDesc)))
	})
	return file_aegis_v1_authz_proto_rawDescData
}

var file_aegis_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aegis_v1_authz_proto_goTypes = []any{
	(*Instance)(nil), // 0: aegis.v1.Instance
	(*Subject)(nil),  // 1: aegis.v1.Subject
	(*Tuple)(nil),    // 2: aegis.v1.Tuple
}
var file_aegis_v1_authz_proto_depIdxs = []int32{
	0, // 0: aegis.v1.Subject.instance:type_name -> aegis.v1.Instance
	0, // 1: aegis.v1.Tuple.resource:type_name -> aegis.v1.Instance
	1, // 2: aegis.v1.Tuple.subject:type_name -> aegis.v1.Subject
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aegis_v1_authz_proto_init() }
func file_aegis_v1_authz_proto_init() {
	if File_aegis_v1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_authz_proto_rawDesc), len(file_aegis_v1_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aegis_v1_authz_proto_goTypes,
		DependencyIndexes: file_aegis_v1_authz_proto_depIdxs,
		MessageInfos:      file_aegis_v1_authz_proto_msgTypes,
	}.Build()
	File_aegis_v1_authz_proto = out.File
	file_aegis_v1_authz_proto_goTypes = nil
	file_aegis_v1_authz_proto_depIdxs = nil
}
