// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/consistency.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConsistencyToken is an opaque token representing a specific "revision" (point in time)
// in the Aegis engine. Returned on every write operation and usable in subsequent reads
// to enforce consistency guarantees against the New Enemy Problem.
type ConsistencyToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque string encoding a datastore revision. Treat as opaque —
	// do not parse or construct manually.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsistencyToken) Reset() {
	*x = ConsistencyToken{}
	mi := &file_aegis_v1_consistency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsistencyToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistencyToken) ProtoMessage() {}

func (x *ConsistencyToken) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_consistency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistencyToken.ProtoReflect.Descriptor instead.
func (*ConsistencyToken) Descriptor() ([]byte, []int) {
	return file_aegis_v1_consistency_proto_rawDescGZIP(), []int{0}
}

func (x *ConsistencyToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Consistency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Strategy:
	//
	//	*Consistency_MinimizeLatency
	//	*Consistency_FresherThan
	//	*Consistency_FullyConsistent
	Strategy      isConsistency_Strategy `protobuf_oneof:"strategy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consistency) Reset() {
	*x = Consistency{}
	mi := &file_aegis_v1_consistency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consistency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consistency) ProtoMessage() {}

func (x *Consistency) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_consistency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consistency.ProtoReflect.Descriptor instead.
func (*Consistency) Descriptor() ([]byte, []int) {
	return file_aegis_v1_consistency_proto_rawDescGZIP(), []int{1}
}

func (x *Consistency) GetStrategy() isConsistency_Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *Consistency) GetMinimizeLatency() bool {
	if x != nil {
		if x, ok := x.Strategy.(*Consistency_MinimizeLatency); ok {
			return x.MinimizeLatency
		}
	}
	return false
}

func (x *Consistency) GetFresherThan() *ConsistencyToken {
	if x != nil {
		if x, ok := x.Strategy.(*Consistency_FresherThan); ok {
			return x.FresherThan
		}
	}
	return nil
}

func (x *Consistency) GetFullyConsistent() bool {
	if x != nil {
		if x, ok := x.Strategy.(*Consistency_FullyConsistent); ok {
			return x.FullyConsistent
		}
	}
	return false
}

type isConsistency_Strategy interface {
	isConsistency_Strategy()
}

type Consistency_MinimizeLatency struct {
	// No freshness guarantee. Minimizes latency by allowing stale reads.
	// Use for non-critical reads where performance dominates correctness.
	MinimizeLatency bool `protobuf:"varint,1,opt,name=minimize_latency,json=minimizeLatency,proto3,oneof"`
}

type Consistency_FresherThan struct {
	// Ensures the read reflects at least the state at the time the token was issued.
	// Use when causal ordering must be preserved across a write/read pair.
	FresherThan *ConsistencyToken `protobuf:"bytes,2,opt,name=fresher_than,json=fresherThan,proto3,oneof"`
}

type Consistency_FullyConsistent struct {
	// Ensures the read reflects the fully consistent current state.
	// Bypasses all caching. Use sparingly on the critical path.
	FullyConsistent bool `protobuf:"varint,3,opt,name=fully_consistent,json=fullyConsistent,proto3,oneof"`
}

func (*Consistency_MinimizeLatency) isConsistency_Strategy() {}

func (*Consistency_FresherThan) isConsistency_Strategy() {}

func (*Consistency_FullyConsistent) isConsistency_Strategy() {}

var File_aegis_v1_consistency_proto protoreflect.FileDescriptor

const file_aegis_v1_consistency_proto_rawDesc = "" +
	"\n" +
	"\x1aaegis/v1/consistency.proto\x12\baegis.v1\x1a\x1bbuf/validate/validate.proto\"0\n" +
	"\x10ConsistencyToken\x12\x1c\n" +
	"\x05token\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05token\"\xc6\x01\n" +
	"\vConsistency\x124\n" +
	"\x10minimize_latency\x18\x01 \x01(\bB\a\xbaH\x04j\x02\b\x01H\x00R\x0fminimizeLatency\x12?\n" +
	"\ffresher_than\x18\x02 \x01(\v2\x1a.aegis.v1.ConsistencyTokenH\x00R\vfresherThan\x124\n" +
	"\x10fully_consistent\x18\x03 \x01(\bB\a\xbaH\x04j\x02\b\x01H\x00R\x0ffullyConsistentB\n" +
	"\n" +
	"\bstrategyB+Z)github.com/aegis-run/aegis/proto/aegis/v1b\x06proto3"

var (
	file_aegis_v1_consistency_proto_rawDescOnce sync.Once
	file_aegis_v1_consistency_proto_rawDescData []byte
)

func file_aegis_v1_consistency_proto_rawDescGZIP() []byte {
	file_aegis_v1_consistency_proto_rawDescOnce.Do(func() {
		file_aegis_v1_consistency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_consistency_proto_rawDesc), len(file_aegis_v1_consistency_proto_rawDesc)))
	})
	return file_aegis_v1_consistency_proto_rawDescData
}

var file_aegis_v1_consistency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aegis_v1_consistency_proto_goTypes = []any{
	(*ConsistencyToken)(nil), // 0: aegis.v1.ConsistencyToken
	(*Consistency)(nil),      // 1: aegis.v1.Consistency
}
var file_aegis_v1_consistency_proto_depIdxs = []int32{
	0, // 0: aegis.v1.Consistency.fresher_than:type_name -> aegis.v1.ConsistencyToken
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aegis_v1_consistency_proto_init() }
func file_aegis_v1_consistency_proto_init() {
	if File_aegis_v1_consistency_proto != nil {
		return
	}
	file_aegis_v1_consistency_proto_msgTypes[1].OneofWrappers = []any{
		(*Consistency_MinimizeLatency)(nil),
		(*Consistency_FresherThan)(nil),
		(*Consistency_FullyConsistent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_consistency_proto_rawDesc), len(file_aegis_v1_consistency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aegis_v1_consistency_proto_goTypes,
		DependencyIndexes: file_aegis_v1_consistency_proto_depIdxs,
		MessageInfos:      file_aegis_v1_consistency_proto_msgTypes,
	}.Build()
	File_aegis_v1_consistency_proto = out.File
	file_aegis_v1_consistency_proto_goTypes = nil
	file_aegis_v1_consistency_proto_depIdxs = nil
}
