// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/pagination.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reusable pagination request parameters.
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Continuation cursor from previous response.
	Cursor *Cursor `protobuf:"bytes,1,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	// Maximum number of results to return (default: 50, max: 1000).
	Limit         *uint32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_aegis_v1_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_aegis_v1_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *Pagination) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

// Reusable pagination response parameters.
type Page struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cursor to retrieve next page (absent if no more results).
	NextCursor *Cursor `protobuf:"bytes,1,opt,name=next_cursor,proto3,oneof" json:"next_cursor,omitempty"`
	// Number of results in this page.
	Count uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Total number of results (if known, otherwise 0).
	Total         *uint32 `protobuf:"varint,3,opt,name=total,proto3,oneof" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_aegis_v1_pagination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_pagination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_aegis_v1_pagination_proto_rawDescGZIP(), []int{1}
}

func (x *Page) GetNextCursor() *Cursor {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

func (x *Page) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Page) GetTotal() uint32 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

// Cursor is an opaque token representing a position in a result set.
// Serialized and base64-encoded to form the page 'token'.
type Cursor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The opaque value of the cursor.
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_aegis_v1_pagination_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_pagination_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_aegis_v1_pagination_proto_rawDescGZIP(), []int{2}
}

func (x *Cursor) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_aegis_v1_pagination_proto protoreflect.FileDescriptor

const file_aegis_v1_pagination_proto_rawDesc = "" +
	"\n" +
	"\x19aegis/v1/pagination.proto\x12\baegis.v1\x1a\x1bbuf/validate/validate.proto\"u\n" +
	"\n" +
	"Pagination\x12-\n" +
	"\x06cursor\x18\x01 \x01(\v2\x10.aegis.v1.CursorH\x00R\x06cursor\x88\x01\x01\x12#\n" +
	"\x05limit\x18\x02 \x01(\rB\b\xbaH\x05*\x03\x18\xe8\aH\x01R\x05limit\x88\x01\x01B\t\n" +
	"\a_cursorB\b\n" +
	"\x06_limit\"\x8a\x01\n" +
	"\x04Page\x127\n" +
	"\vnext_cursor\x18\x01 \x01(\v2\x10.aegis.v1.CursorH\x00R\vnext_cursor\x88\x01\x01\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x19\n" +
	"\x05total\x18\x03 \x01(\rH\x01R\x05total\x88\x01\x01B\x0e\n" +
	"\f_next_cursorB\b\n" +
	"\x06_total\"\x1e\n" +
	"\x06Cursor\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05valueB+Z)github.com/aegis-run/aegis/proto/aegis/v1b\x06proto3"

var (
	file_aegis_v1_pagination_proto_rawDescOnce sync.Once
	file_aegis_v1_pagination_proto_rawDescData []byte
)

func file_aegis_v1_pagination_proto_rawDescGZIP() []byte {
	file_aegis_v1_pagination_proto_rawDescOnce.Do(func() {
		file_aegis_v1_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_pagination_proto_rawDesc), len(file_aegis_v1_pagination_proto_rawDesc)))
	})
	return file_aegis_v1_pagination_proto_rawDescData
}

var file_aegis_v1_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aegis_v1_pagination_proto_goTypes = []any{
	(*Pagination)(nil), // 0: aegis.v1.Pagination
	(*Page)(nil),       // 1: aegis.v1.Page
	(*Cursor)(nil),     // 2: aegis.v1.Cursor
}
var file_aegis_v1_pagination_proto_depIdxs = []int32{
	2, // 0: aegis.v1.Pagination.cursor:type_name -> aegis.v1.Cursor
	2, // 1: aegis.v1.Page.next_cursor:type_name -> aegis.v1.Cursor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aegis_v1_pagination_proto_init() }
func file_aegis_v1_pagination_proto_init() {
	if File_aegis_v1_pagination_proto != nil {
		return
	}
	file_aegis_v1_pagination_proto_msgTypes[0].OneofWrappers = []any{}
	file_aegis_v1_pagination_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_pagination_proto_rawDesc), len(file_aegis_v1_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aegis_v1_pagination_proto_goTypes,
		DependencyIndexes: file_aegis_v1_pagination_proto_depIdxs,
		MessageInfos:      file_aegis_v1_pagination_proto_msgTypes,
	}.Build()
	File_aegis_v1_pagination_proto = out.File
	file_aegis_v1_pagination_proto_goTypes = nil
	file_aegis_v1_pagination_proto_depIdxs = nil
}
