// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/v1/schema.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Root message for exporting a validated `.aes` schema.
//
// Contains all type definitions with their relations and computed permissions.
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All type definitions in the schema, e.g., `user`, `team`, `repository`.
	Types         []*TypeDefinition `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_aegis_v1_schema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Schema) GetTypes() []*TypeDefinition {
	if x != nil {
		return x.Types
	}
	return nil
}

// A single `type` definition from the schema.
type TypeDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type name, e.g., `user`, `team`, `repository`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Direct relations (`let` members) that store actor-to-resource mappings.
	Relations []*Relation `protobuf:"bytes,2,rep,name=relations,proto3" json:"relations,omitempty"`
	// Computed permissions (`def` members) derived from relations via expressions.
	Permissions   []*Permission `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDefinition) Reset() {
	*x = TypeDefinition{}
	mi := &file_aegis_v1_schema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDefinition) ProtoMessage() {}

func (x *TypeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDefinition.ProtoReflect.Descriptor instead.
func (*TypeDefinition) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{1}
}

func (x *TypeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeDefinition) GetRelations() []*Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *TypeDefinition) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// A direct relation defined via `let` in a type definition.
//
// Relations map actors (users, teams) to resource instances. Each relation specifies
// which actor types are allowed.
type Relation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Actors        []*ActorType           `protobuf:"bytes,2,rep,name=actors,proto3" json:"actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relation) Reset() {
	*x = Relation{}
	mi := &file_aegis_v1_schema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relation) ProtoMessage() {}

func (x *Relation) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relation.ProtoReflect.Descriptor instead.
func (*Relation) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Relation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Relation) GetActors() []*ActorType {
	if x != nil {
		return x.Actors
	}
	return nil
}

// Specifies an actor type allowed in a relation. An actor type can be either:
// - A direct type reference (e.g., `user`);
// - A userset type reference (e.g., `team::member`);
type ActorType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actor type specification.
	//
	// Types that are valid to be assigned to Actor:
	//
	//	*ActorType_Direct
	//	*ActorType_Userset
	Actor         isActorType_Actor `protobuf_oneof:"actor"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorType) Reset() {
	*x = ActorType{}
	mi := &file_aegis_v1_schema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorType) ProtoMessage() {}

func (x *ActorType) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorType.ProtoReflect.Descriptor instead.
func (*ActorType) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{3}
}

func (x *ActorType) GetActor() isActorType_Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ActorType) GetDirect() string {
	if x != nil {
		if x, ok := x.Actor.(*ActorType_Direct); ok {
			return x.Direct
		}
	}
	return ""
}

func (x *ActorType) GetUserset() *UsersetType {
	if x != nil {
		if x, ok := x.Actor.(*ActorType_Userset); ok {
			return x.Userset
		}
	}
	return nil
}

type isActorType_Actor interface {
	isActorType_Actor()
}

type ActorType_Direct struct {
	// Direct type reference (e.g., `user`)
	Direct string `protobuf:"bytes,1,opt,name=direct,proto3,oneof"`
}

type ActorType_Userset struct {
	// Userset type reference (e.g., `team::member`)
	Userset *UsersetType `protobuf:"bytes,2,opt,name=userset,proto3,oneof"`
}

func (*ActorType_Direct) isActorType_Actor() {}

func (*ActorType_Userset) isActorType_Actor() {}

// A userset type reference: `type::member`. References a relation on another type as the
// actor.
type UsersetType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The referenced type name
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The relation/member on the referenced type.
	Member        string `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersetType) Reset() {
	*x = UsersetType{}
	mi := &file_aegis_v1_schema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersetType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersetType) ProtoMessage() {}

func (x *UsersetType) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersetType.ProtoReflect.Descriptor instead.
func (*UsersetType) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{4}
}

func (x *UsersetType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UsersetType) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

// A computed permission defined via `def` in a type definition.
//
// Permissions are derived from relations through boolean expressions
// involving unions, intersections, differences, and traversals.
type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expr          *Expression            `protobuf:"bytes,2,opt,name=expr,proto3" json:"expr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_aegis_v1_schema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{5}
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetExpr() *Expression {
	if x != nil {
		return x.Expr
	}
	return nil
}

// A boolean expression for computing permissions.
type Expression struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The expr kind
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Expression_Union
	//	*Expression_Intersection
	//	*Expression_Difference
	//	*Expression_Term
	Kind          isExpression_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expression) Reset() {
	*x = Expression{}
	mi := &file_aegis_v1_schema_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{6}
}

func (x *Expression) GetKind() isExpression_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Expression) GetUnion() *UnionExpr {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Union); ok {
			return x.Union
		}
	}
	return nil
}

func (x *Expression) GetIntersection() *IntersectionExpr {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Intersection); ok {
			return x.Intersection
		}
	}
	return nil
}

func (x *Expression) GetDifference() *DifferenceExpr {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Difference); ok {
			return x.Difference
		}
	}
	return nil
}

func (x *Expression) GetTerm() *TermExpr {
	if x != nil {
		if x, ok := x.Kind.(*Expression_Term); ok {
			return x.Term
		}
	}
	return nil
}

type isExpression_Kind interface {
	isExpression_Kind()
}

type Expression_Union struct {
	// Union operation: lhs | rhs
	Union *UnionExpr `protobuf:"bytes,1,opt,name=union,proto3,oneof"`
}

type Expression_Intersection struct {
	// Intersection operation: lhs & rhs
	Intersection *IntersectionExpr `protobuf:"bytes,2,opt,name=intersection,proto3,oneof"`
}

type Expression_Difference struct {
	// Difference operation: lhs - rhs
	Difference *DifferenceExpr `protobuf:"bytes,3,opt,name=difference,proto3,oneof"`
}

type Expression_Term struct {
	// A single term (leaf node in the expression tree)
	Term *TermExpr `protobuf:"bytes,4,opt,name=term,proto3,oneof"`
}

func (*Expression_Union) isExpression_Kind() {}

func (*Expression_Intersection) isExpression_Kind() {}

func (*Expression_Difference) isExpression_Kind() {}

func (*Expression_Term) isExpression_Kind() {}

// Union expression: combines multiple expressions with OR semantics.
//
// An actor has permission if _any_ of the operands evaluates to true.
type UnionExpr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operands to union.
	Terms         []*Expression `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnionExpr) Reset() {
	*x = UnionExpr{}
	mi := &file_aegis_v1_schema_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionExpr) ProtoMessage() {}

func (x *UnionExpr) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionExpr.ProtoReflect.Descriptor instead.
func (*UnionExpr) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{7}
}

func (x *UnionExpr) GetTerms() []*Expression {
	if x != nil {
		return x.Terms
	}
	return nil
}

// Combines multiple expressions with AND semantics.
//
// An actor has permission only if _all_ of the operands evaluate to true.
type IntersectionExpr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The operands to intersect.
	Terms         []*Expression `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntersectionExpr) Reset() {
	*x = IntersectionExpr{}
	mi := &file_aegis_v1_schema_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntersectionExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntersectionExpr) ProtoMessage() {}

func (x *IntersectionExpr) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntersectionExpr.ProtoReflect.Descriptor instead.
func (*IntersectionExpr) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{8}
}

func (x *IntersectionExpr) GetTerms() []*Expression {
	if x != nil {
		return x.Terms
	}
	return nil
}

// Difference (exclusion) expression: subtracts one expression from another.
//
// An actor has permission if the LHS evaluates to true AND the RHS evaluates to false.
// Equivalent to set-difference operator.
type DifferenceExpr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Left-hand side of the difference.
	Lhs *Expression `protobuf:"bytes,1,opt,name=lhs,proto3" json:"lhs,omitempty"`
	// Right-hand side of the difference (the exclusion set).
	Rhs           *Expression `protobuf:"bytes,2,opt,name=rhs,proto3" json:"rhs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifferenceExpr) Reset() {
	*x = DifferenceExpr{}
	mi := &file_aegis_v1_schema_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferenceExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferenceExpr) ProtoMessage() {}

func (x *DifferenceExpr) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifferenceExpr.ProtoReflect.Descriptor instead.
func (*DifferenceExpr) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{9}
}

func (x *DifferenceExpr) GetLhs() *Expression {
	if x != nil {
		return x.Lhs
	}
	return nil
}

func (x *DifferenceExpr) GetRhs() *Expression {
	if x != nil {
		return x.Rhs
	}
	return nil
}

// A single term in an expression.
//
// Terms are the leaf nodes of the permission expression tree. They represent
// either a self-reference to a relation (`.relation`) or a traversal to a
// computed permission on a related type (`.relation.permission`).
type TermExpr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The term variant.
	//
	// Types that are valid to be assigned to Term:
	//
	//	*TermExpr_SelfRef
	//	*TermExpr_Traversal
	Term          isTermExpr_Term `protobuf_oneof:"term"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermExpr) Reset() {
	*x = TermExpr{}
	mi := &file_aegis_v1_schema_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermExpr) ProtoMessage() {}

func (x *TermExpr) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermExpr.ProtoReflect.Descriptor instead.
func (*TermExpr) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{10}
}

func (x *TermExpr) GetTerm() isTermExpr_Term {
	if x != nil {
		return x.Term
	}
	return nil
}

func (x *TermExpr) GetSelfRef() *SelfRef {
	if x != nil {
		if x, ok := x.Term.(*TermExpr_SelfRef); ok {
			return x.SelfRef
		}
	}
	return nil
}

func (x *TermExpr) GetTraversal() *Traversal {
	if x != nil {
		if x, ok := x.Term.(*TermExpr_Traversal); ok {
			return x.Traversal
		}
	}
	return nil
}

type isTermExpr_Term interface {
	isTermExpr_Term()
}

type TermExpr_SelfRef struct {
	// Self-reference: `.relation` (valid only in `def` bodies)
	SelfRef *SelfRef `protobuf:"bytes,1,opt,name=self_ref,json=selfRef,proto3,oneof"`
}

type TermExpr_Traversal struct {
	// Traversal: `.relation.permission` (valid only in `def` bodies)
	Traversal *Traversal `protobuf:"bytes,2,opt,name=traversal,proto3,oneof"`
}

func (*TermExpr_SelfRef) isTermExpr_Term() {}

func (*TermExpr_Traversal) isTermExpr_Term() {}

// Self-reference term: `.relation`.
//
// References a direct relation on the current type. Valid only in `def` bodies.
type SelfRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The relation being referenced.
	Relation      string `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfRef) Reset() {
	*x = SelfRef{}
	mi := &file_aegis_v1_schema_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfRef) ProtoMessage() {}

func (x *SelfRef) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfRef.ProtoReflect.Descriptor instead.
func (*SelfRef) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{11}
}

func (x *SelfRef) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

// Traversal term: `.relation.permission`.
//
// Traverses from a relation to a computed permission on the related type.
// Valid only in `def` bodies. This enables permission inheritance across
// type boundaries.
type Traversal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The relation to traverse, e.g., `"parent"`.
	Relation string `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	// The permission to access on the related type, e.g., `"change_team_name"`.
	Permission    string `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Traversal) Reset() {
	*x = Traversal{}
	mi := &file_aegis_v1_schema_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Traversal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Traversal) ProtoMessage() {}

func (x *Traversal) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_schema_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Traversal.ProtoReflect.Descriptor instead.
func (*Traversal) Descriptor() ([]byte, []int) {
	return file_aegis_v1_schema_proto_rawDescGZIP(), []int{12}
}

func (x *Traversal) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Traversal) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

var File_aegis_v1_schema_proto protoreflect.FileDescriptor

const file_aegis_v1_schema_proto_rawDesc = "" +
	"\n" +
	"\x15aegis/v1/schema.proto\x12\baegis.v1\x1a\x1bbuf/validate/validate.proto\"B\n" +
	"\x06Schema\x128\n" +
	"\x05types\x18\x01 \x03(\v2\x18.aegis.v1.TypeDefinitionB\b\xbaH\x05\x92\x01\x02\b\x01R\x05types\"\xbc\x01\n" +
	"\x0eTypeDefinition\x12@\n" +
	"\x04name\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\x04name\x120\n" +
	"\trelations\x18\x02 \x03(\v2\x12.aegis.v1.RelationR\trelations\x126\n" +
	"\vpermissions\x18\x03 \x03(\v2\x14.aegis.v1.PermissionR\vpermissions\"\x83\x01\n" +
	"\bRelation\x12@\n" +
	"\x04name\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\x04name\x125\n" +
	"\x06actors\x18\x02 \x03(\v2\x13.aegis.v1.ActorTypeB\b\xbaH\x05\x92\x01\x02\b\x01R\x06actors\"\x8f\x01\n" +
	"\tActorType\x12F\n" +
	"\x06direct\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$H\x00R\x06direct\x121\n" +
	"\auserset\x18\x02 \x01(\v2\x15.aegis.v1.UsersetTypeH\x00R\ausersetB\a\n" +
	"\x05actor\"\x95\x01\n" +
	"\vUsersetType\x12@\n" +
	"\x04type\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\x04type\x12D\n" +
	"\x06member\x18\x02 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\x06member\"\x80\x01\n" +
	"\n" +
	"Permission\x12@\n" +
	"\x04name\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\x04name\x120\n" +
	"\x04expr\x18\x02 \x01(\v2\x14.aegis.v1.ExpressionB\x06\xbaH\x03\xc8\x01\x01R\x04expr\"\xe9\x01\n" +
	"\n" +
	"Expression\x12+\n" +
	"\x05union\x18\x01 \x01(\v2\x13.aegis.v1.UnionExprH\x00R\x05union\x12@\n" +
	"\fintersection\x18\x02 \x01(\v2\x1a.aegis.v1.IntersectionExprH\x00R\fintersection\x12:\n" +
	"\n" +
	"difference\x18\x03 \x01(\v2\x18.aegis.v1.DifferenceExprH\x00R\n" +
	"difference\x12(\n" +
	"\x04term\x18\x04 \x01(\v2\x12.aegis.v1.TermExprH\x00R\x04termB\x06\n" +
	"\x04kind\"A\n" +
	"\tUnionExpr\x124\n" +
	"\x05terms\x18\x01 \x03(\v2\x14.aegis.v1.ExpressionB\b\xbaH\x05\x92\x01\x02\b\x02R\x05terms\"H\n" +
	"\x10IntersectionExpr\x124\n" +
	"\x05terms\x18\x01 \x03(\v2\x14.aegis.v1.ExpressionB\b\xbaH\x05\x92\x01\x02\b\x02R\x05terms\"p\n" +
	"\x0eDifferenceExpr\x12.\n" +
	"\x03lhs\x18\x01 \x01(\v2\x14.aegis.v1.ExpressionB\x06\xbaH\x03\xc8\x01\x01R\x03lhs\x12.\n" +
	"\x03rhs\x18\x02 \x01(\v2\x14.aegis.v1.ExpressionB\x06\xbaH\x03\xc8\x01\x01R\x03rhs\"w\n" +
	"\bTermExpr\x12.\n" +
	"\bself_ref\x18\x01 \x01(\v2\x11.aegis.v1.SelfRefH\x00R\aselfRef\x123\n" +
	"\ttraversal\x18\x02 \x01(\v2\x13.aegis.v1.TraversalH\x00R\ttraversalB\x06\n" +
	"\x04term\"S\n" +
	"\aSelfRef\x12H\n" +
	"\brelation\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\brelation\"\xa3\x01\n" +
	"\tTraversal\x12H\n" +
	"\brelation\x18\x01 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\brelation\x12L\n" +
	"\n" +
	"permission\x18\x02 \x01(\tB,\xbaH)r'\x10\x01(@2!^[a-z]([a-z0-9_]{0,62}[a-z0-9])?$R\n" +
	"permissionB+Z)github.com/aegis-run/aegis/proto/aegis/v1b\x06proto3"

var (
	file_aegis_v1_schema_proto_rawDescOnce sync.Once
	file_aegis_v1_schema_proto_rawDescData []byte
)

func file_aegis_v1_schema_proto_rawDescGZIP() []byte {
	file_aegis_v1_schema_proto_rawDescOnce.Do(func() {
		file_aegis_v1_schema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_schema_proto_rawDesc), len(file_aegis_v1_schema_proto_rawDesc)))
	})
	return file_aegis_v1_schema_proto_rawDescData
}

var file_aegis_v1_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_aegis_v1_schema_proto_goTypes = []any{
	(*Schema)(nil),           // 0: aegis.v1.Schema
	(*TypeDefinition)(nil),   // 1: aegis.v1.TypeDefinition
	(*Relation)(nil),         // 2: aegis.v1.Relation
	(*ActorType)(nil),        // 3: aegis.v1.ActorType
	(*UsersetType)(nil),      // 4: aegis.v1.UsersetType
	(*Permission)(nil),       // 5: aegis.v1.Permission
	(*Expression)(nil),       // 6: aegis.v1.Expression
	(*UnionExpr)(nil),        // 7: aegis.v1.UnionExpr
	(*IntersectionExpr)(nil), // 8: aegis.v1.IntersectionExpr
	(*DifferenceExpr)(nil),   // 9: aegis.v1.DifferenceExpr
	(*TermExpr)(nil),         // 10: aegis.v1.TermExpr
	(*SelfRef)(nil),          // 11: aegis.v1.SelfRef
	(*Traversal)(nil),        // 12: aegis.v1.Traversal
}
var file_aegis_v1_schema_proto_depIdxs = []int32{
	1,  // 0: aegis.v1.Schema.types:type_name -> aegis.v1.TypeDefinition
	2,  // 1: aegis.v1.TypeDefinition.relations:type_name -> aegis.v1.Relation
	5,  // 2: aegis.v1.TypeDefinition.permissions:type_name -> aegis.v1.Permission
	3,  // 3: aegis.v1.Relation.actors:type_name -> aegis.v1.ActorType
	4,  // 4: aegis.v1.ActorType.userset:type_name -> aegis.v1.UsersetType
	6,  // 5: aegis.v1.Permission.expr:type_name -> aegis.v1.Expression
	7,  // 6: aegis.v1.Expression.union:type_name -> aegis.v1.UnionExpr
	8,  // 7: aegis.v1.Expression.intersection:type_name -> aegis.v1.IntersectionExpr
	9,  // 8: aegis.v1.Expression.difference:type_name -> aegis.v1.DifferenceExpr
	10, // 9: aegis.v1.Expression.term:type_name -> aegis.v1.TermExpr
	6,  // 10: aegis.v1.UnionExpr.terms:type_name -> aegis.v1.Expression
	6,  // 11: aegis.v1.IntersectionExpr.terms:type_name -> aegis.v1.Expression
	6,  // 12: aegis.v1.DifferenceExpr.lhs:type_name -> aegis.v1.Expression
	6,  // 13: aegis.v1.DifferenceExpr.rhs:type_name -> aegis.v1.Expression
	11, // 14: aegis.v1.TermExpr.self_ref:type_name -> aegis.v1.SelfRef
	12, // 15: aegis.v1.TermExpr.traversal:type_name -> aegis.v1.Traversal
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_aegis_v1_schema_proto_init() }
func file_aegis_v1_schema_proto_init() {
	if File_aegis_v1_schema_proto != nil {
		return
	}
	file_aegis_v1_schema_proto_msgTypes[3].OneofWrappers = []any{
		(*ActorType_Direct)(nil),
		(*ActorType_Userset)(nil),
	}
	file_aegis_v1_schema_proto_msgTypes[6].OneofWrappers = []any{
		(*Expression_Union)(nil),
		(*Expression_Intersection)(nil),
		(*Expression_Difference)(nil),
		(*Expression_Term)(nil),
	}
	file_aegis_v1_schema_proto_msgTypes[10].OneofWrappers = []any{
		(*TermExpr_SelfRef)(nil),
		(*TermExpr_Traversal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_schema_proto_rawDesc), len(file_aegis_v1_schema_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aegis_v1_schema_proto_goTypes,
		DependencyIndexes: file_aegis_v1_schema_proto_depIdxs,
		MessageInfos:      file_aegis_v1_schema_proto_msgTypes,
	}.Build()
	File_aegis_v1_schema_proto = out.File
	file_aegis_v1_schema_proto_goTypes = nil
	file_aegis_v1_schema_proto_depIdxs = nil
}
