// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aegis/schema/v1/api.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/aegis-run/aegis/proto/aegis/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A content-addressed revision token for a compiled schema version.
// Computed server-side as the SHA-256 hash of the stored schema bytes.
// Used to bind permission checks to a specific schema snapshot.
type SchemaHash struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64-encoded SHA-256 digest.
	Digest        string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaHash) Reset() {
	*x = SchemaHash{}
	mi := &file_aegis_schema_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaHash) ProtoMessage() {}

func (x *SchemaHash) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_schema_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaHash.ProtoReflect.Descriptor instead.
func (*SchemaHash) Descriptor() ([]byte, []int) {
	return file_aegis_schema_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaHash) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// WriteSchemaRequest carries the compiled schema IR produced by the AES compiler.
// The revision token is computed server-side from the stored bytes.
type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The compiled schema IR to store.
	Schema        *v1.Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_aegis_schema_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_schema_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_aegis_schema_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *WriteRequest) GetSchema() *v1.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

// WriteSchemaResponse returns the revision token for the stored schema.
type WriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Content-addressed revision token for this schema version.
	Hash *SchemaHash `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// Consistency token representing the datastore revision at the time of write.
	// Pass to subsequent reads to enforce causal consistency.
	WrittenAt     *v1.ConsistencyToken `protobuf:"bytes,2,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_aegis_schema_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_schema_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_aegis_schema_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *WriteResponse) GetHash() *SchemaHash {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *WriteResponse) GetWrittenAt() *v1.ConsistencyToken {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

// GetSchemaRequest specifies which schema version to retrieve.
// If hash is absent, the latest stored schema is returned.
type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Revision token of the schema version to retrieve.
	// If absent, the latest schema is returned.
	Hash *SchemaHash `protobuf:"bytes,1,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	// Consistency requirement for this read.
	// If absent, defaults to fully_consistent.
	Consistency   *v1.Consistency `protobuf:"bytes,2,opt,name=consistency,proto3,oneof" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_aegis_schema_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_schema_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_aegis_schema_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequest) GetHash() *SchemaHash {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ReadRequest) GetConsistency() *v1.Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

// GetSchemaResponse returns the requested schema and its revision metadata.
type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The structured schema IR, ready for consumption by the evaluation engine.
	Schema *v1.Schema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	// Revision token of this schema version.
	Hash *SchemaHash `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// Consistency token representing the datastore revision at the time of write.
	// Pass to subsequent reads to enforce causal consistency.
	WrittenAt     *v1.ConsistencyToken `protobuf:"bytes,3,opt,name=written_at,json=writtenAt,proto3" json:"written_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_aegis_schema_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_schema_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_aegis_schema_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *ReadResponse) GetSchema() *v1.Schema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ReadResponse) GetHash() *SchemaHash {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ReadResponse) GetWrittenAt() *v1.ConsistencyToken {
	if x != nil {
		return x.WrittenAt
	}
	return nil
}

var File_aegis_schema_v1_api_proto protoreflect.FileDescriptor

const file_aegis_schema_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x19aegis/schema/v1/api.proto\x12\x0faegis.schema.v1\x1a\x1aaegis/v1/consistency.proto\x1a\x15aegis/v1/schema.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\n" +
	"SchemaHash\x128\n" +
	"\x06digest\x18\x01 \x01(\tB \xbaH\x1dr\x1b2\x16^[A-Za-z0-9+/_-]{43}=$\x98\x01,R\x06digest\"@\n" +
	"\fWriteRequest\x120\n" +
	"\x06schema\x18\x01 \x01(\v2\x10.aegis.v1.SchemaB\x06\xbaH\x03\xc8\x01\x01R\x06schema\"{\n" +
	"\rWriteResponse\x12/\n" +
	"\x04hash\x18\x01 \x01(\v2\x1b.aegis.schema.v1.SchemaHashR\x04hash\x129\n" +
	"\n" +
	"written_at\x18\x02 \x01(\v2\x1a.aegis.v1.ConsistencyTokenR\twrittenAt\"\x9a\x01\n" +
	"\vReadRequest\x124\n" +
	"\x04hash\x18\x01 \x01(\v2\x1b.aegis.schema.v1.SchemaHashH\x00R\x04hash\x88\x01\x01\x12<\n" +
	"\vconsistency\x18\x02 \x01(\v2\x15.aegis.v1.ConsistencyH\x01R\vconsistency\x88\x01\x01B\a\n" +
	"\x05_hashB\x0e\n" +
	"\f_consistency\"\xa4\x01\n" +
	"\fReadResponse\x12(\n" +
	"\x06schema\x18\x01 \x01(\v2\x10.aegis.v1.SchemaR\x06schema\x12/\n" +
	"\x04hash\x18\x02 \x01(\v2\x1b.aegis.schema.v1.SchemaHashR\x04hash\x129\n" +
	"\n" +
	"written_at\x18\x03 \x01(\v2\x1a.aegis.v1.ConsistencyTokenR\twrittenAt2\xcb\x01\n" +
	"\x06Schema\x12\\\n" +
	"\x04Read\x12\x1c.aegis.schema.v1.ReadRequest\x1a\x1d.aegis.schema.v1.ReadResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/schema/read\x12c\n" +
	"\x05Write\x12\x1d.aegis.schema.v1.WriteRequest\x1a\x1e.aegis.schema.v1.WriteResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/schema/writeB2Z0github.com/aegis-run/aegis/proto/aegis/schema/v1b\x06proto3"

var (
	file_aegis_schema_v1_api_proto_rawDescOnce sync.Once
	file_aegis_schema_v1_api_proto_rawDescData []byte
)

func file_aegis_schema_v1_api_proto_rawDescGZIP() []byte {
	file_aegis_schema_v1_api_proto_rawDescOnce.Do(func() {
		file_aegis_schema_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_schema_v1_api_proto_rawDesc), len(file_aegis_schema_v1_api_proto_rawDesc)))
	})
	return file_aegis_schema_v1_api_proto_rawDescData
}

var file_aegis_schema_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_aegis_schema_v1_api_proto_goTypes = []any{
	(*SchemaHash)(nil),          // 0: aegis.schema.v1.SchemaHash
	(*WriteRequest)(nil),        // 1: aegis.schema.v1.WriteRequest
	(*WriteResponse)(nil),       // 2: aegis.schema.v1.WriteResponse
	(*ReadRequest)(nil),         // 3: aegis.schema.v1.ReadRequest
	(*ReadResponse)(nil),        // 4: aegis.schema.v1.ReadResponse
	(*v1.Schema)(nil),           // 5: aegis.v1.Schema
	(*v1.ConsistencyToken)(nil), // 6: aegis.v1.ConsistencyToken
	(*v1.Consistency)(nil),      // 7: aegis.v1.Consistency
}
var file_aegis_schema_v1_api_proto_depIdxs = []int32{
	5,  // 0: aegis.schema.v1.WriteRequest.schema:type_name -> aegis.v1.Schema
	0,  // 1: aegis.schema.v1.WriteResponse.hash:type_name -> aegis.schema.v1.SchemaHash
	6,  // 2: aegis.schema.v1.WriteResponse.written_at:type_name -> aegis.v1.ConsistencyToken
	0,  // 3: aegis.schema.v1.ReadRequest.hash:type_name -> aegis.schema.v1.SchemaHash
	7,  // 4: aegis.schema.v1.ReadRequest.consistency:type_name -> aegis.v1.Consistency
	5,  // 5: aegis.schema.v1.ReadResponse.schema:type_name -> aegis.v1.Schema
	0,  // 6: aegis.schema.v1.ReadResponse.hash:type_name -> aegis.schema.v1.SchemaHash
	6,  // 7: aegis.schema.v1.ReadResponse.written_at:type_name -> aegis.v1.ConsistencyToken
	3,  // 8: aegis.schema.v1.Schema.Read:input_type -> aegis.schema.v1.ReadRequest
	1,  // 9: aegis.schema.v1.Schema.Write:input_type -> aegis.schema.v1.WriteRequest
	4,  // 10: aegis.schema.v1.Schema.Read:output_type -> aegis.schema.v1.ReadResponse
	2,  // 11: aegis.schema.v1.Schema.Write:output_type -> aegis.schema.v1.WriteResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_aegis_schema_v1_api_proto_init() }
func file_aegis_schema_v1_api_proto_init() {
	if File_aegis_schema_v1_api_proto != nil {
		return
	}
	file_aegis_schema_v1_api_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_schema_v1_api_proto_rawDesc), len(file_aegis_schema_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_schema_v1_api_proto_goTypes,
		DependencyIndexes: file_aegis_schema_v1_api_proto_depIdxs,
		MessageInfos:      file_aegis_schema_v1_api_proto_msgTypes,
	}.Build()
	File_aegis_schema_v1_api_proto = out.File
	file_aegis_schema_v1_api_proto_goTypes = nil
	file_aegis_schema_v1_api_proto_depIdxs = nil
}
