// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consistency.sql

package postgres

import (
	"context"

	"github.com/aegis-run/aegis/pkg/db/postgres/types"
)

const getCurrentXactID = `-- name: GetCurrentXactID :one
SELECT pg_current_xact_id()::xid8
`

// GetCurrentXactID
//
//	SELECT pg_current_xact_id()::xid8
func (q *Queries) GetCurrentXactID(ctx context.Context, db DBTX) (types.XID8, error) {
	row := db.QueryRow(ctx, getCurrentXactID)
	var column_1 types.XID8
	err := row.Scan(&column_1)
	return column_1, err
}

const getSnapshotXmax = `-- name: GetSnapshotXmax :one
SELECT pg_snapshot_xmax(pg_current_snapshot())::xid8
`

// GetSnapshotXmax
//
//	SELECT pg_snapshot_xmax(pg_current_snapshot())::xid8
func (q *Queries) GetSnapshotXmax(ctx context.Context, db DBTX) (types.XID8, error) {
	row := db.QueryRow(ctx, getSnapshotXmax)
	var column_1 types.XID8
	err := row.Scan(&column_1)
	return column_1, err
}

const isXactVisible = `-- name: IsXactVisible :one
SELECT pg_visible_in_snapshot($1::xid8, pg_current_snapshot())::boolean
`

// IsXactVisible
//
//	SELECT pg_visible_in_snapshot($1::xid8, pg_current_snapshot())::boolean
func (q *Queries) IsXactVisible(ctx context.Context, db DBTX, xid types.XID8) (bool, error) {
	row := db.QueryRow(ctx, isXactVisible, xid)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
