// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/aegis-run/aegis/pkg/schema"
)

type Querier interface {
	//GetLatestSchemaVersion
	//
	//  SELECT
	//    s.hash,
	//    s.data,
	//    s.created_at
	//  FROM "schema" s
	//  ORDER BY s.pk DESC
	//  LIMIT 1
	GetLatestSchemaVersion(ctx context.Context, db DBTX) (GetLatestSchemaVersionRow, error)
	//GetSchemaVersionByHash
	//
	//  SELECT
	//    s.hash,
	//    s.data,
	//    s.created_at
	//  FROM "schema" s
	//  WHERE s.hash = $1
	GetSchemaVersionByHash(ctx context.Context, db DBTX, hash schema.Hash) (GetSchemaVersionByHashRow, error)
	//InsertSchemaVersion
	//
	//  INSERT INTO "schema" (
	//    hash, data
	//  ) VALUES (
	//    $1, $2
	//  )
	//  ON CONFLICT (hash) DO NOTHING
	//  RETURNING hash, created_at
	InsertSchemaVersion(ctx context.Context, db DBTX, arg InsertSchemaVersionParams) (InsertSchemaVersionRow, error)
}

var _ Querier = (*Queries)(nil)
