// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/aegis-run/aegis/pkg/schema"
)

type Schema struct {
	Pk        int64       `db:"pk"`
	Hash      schema.Hash `db:"hash"`
	Data      []byte      `db:"data"`
	CreatedAt time.Time   `db:"created_at"`
}
