// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schema.sql

package postgres

import (
	"context"
	"time"

	"github.com/aegis-run/aegis/pkg/schema"
)

const getLatestSchemaVersion = `-- name: GetLatestSchemaVersion :one
SELECT
  s.hash,
  s.data,
  s.created_at
FROM "schema" s
ORDER BY s.pk DESC
LIMIT 1
`

type GetLatestSchemaVersionRow struct {
	Hash      schema.Hash `db:"hash"`
	Data      []byte      `db:"data"`
	CreatedAt time.Time   `db:"created_at"`
}

// GetLatestSchemaVersion
//
//	SELECT
//	  s.hash,
//	  s.data,
//	  s.created_at
//	FROM "schema" s
//	ORDER BY s.pk DESC
//	LIMIT 1
func (q *Queries) GetLatestSchemaVersion(ctx context.Context, db DBTX) (GetLatestSchemaVersionRow, error) {
	row := db.QueryRow(ctx, getLatestSchemaVersion)
	var i GetLatestSchemaVersionRow
	err := row.Scan(&i.Hash, &i.Data, &i.CreatedAt)
	return i, err
}

const getSchemaVersionByHash = `-- name: GetSchemaVersionByHash :one
SELECT
  s.hash,
  s.data,
  s.created_at
FROM "schema" s
WHERE s.hash = $1
`

type GetSchemaVersionByHashRow struct {
	Hash      schema.Hash `db:"hash"`
	Data      []byte      `db:"data"`
	CreatedAt time.Time   `db:"created_at"`
}

// GetSchemaVersionByHash
//
//	SELECT
//	  s.hash,
//	  s.data,
//	  s.created_at
//	FROM "schema" s
//	WHERE s.hash = $1
func (q *Queries) GetSchemaVersionByHash(ctx context.Context, db DBTX, hash schema.Hash) (GetSchemaVersionByHashRow, error) {
	row := db.QueryRow(ctx, getSchemaVersionByHash, hash)
	var i GetSchemaVersionByHashRow
	err := row.Scan(&i.Hash, &i.Data, &i.CreatedAt)
	return i, err
}

const insertSchemaVersion = `-- name: InsertSchemaVersion :one
INSERT INTO "schema" (
  hash, data
) VALUES (
  $1, $2
)
ON CONFLICT (hash) DO NOTHING
RETURNING hash, created_at
`

type InsertSchemaVersionParams struct {
	Hash schema.Hash `db:"hash"`
	Data []byte      `db:"data"`
}

type InsertSchemaVersionRow struct {
	Hash      schema.Hash `db:"hash"`
	CreatedAt time.Time   `db:"created_at"`
}

// InsertSchemaVersion
//
//	INSERT INTO "schema" (
//	  hash, data
//	) VALUES (
//	  $1, $2
//	)
//	ON CONFLICT (hash) DO NOTHING
//	RETURNING hash, created_at
func (q *Queries) InsertSchemaVersion(ctx context.Context, db DBTX, arg InsertSchemaVersionParams) (InsertSchemaVersionRow, error) {
	row := db.QueryRow(ctx, insertSchemaVersion, arg.Hash, arg.Data)
	var i InsertSchemaVersionRow
	err := row.Scan(&i.Hash, &i.CreatedAt)
	return i, err
}
