// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tuple.sql

package postgres

import (
	"context"
)

const deleteTuple = `-- name: DeleteTuple :exec
DELETE FROM "tuple"
WHERE resource_type = $1
  AND resource_id = $2
  AND relation = $3
  AND subject_type = $4
  AND subject_id = $5
  AND subject_permission = $6
`

type DeleteTupleParams struct {
	ResourceType      string `db:"resource_type"`
	ResourceID        string `db:"resource_id"`
	Relation          string `db:"relation"`
	SubjectType       string `db:"subject_type"`
	SubjectID         string `db:"subject_id"`
	SubjectPermission string `db:"subject_permission"`
}

// DeleteTuple
//
//	DELETE FROM "tuple"
//	WHERE resource_type = $1
//	  AND resource_id = $2
//	  AND relation = $3
//	  AND subject_type = $4
//	  AND subject_id = $5
//	  AND subject_permission = $6
func (q *Queries) DeleteTuple(ctx context.Context, db DBTX, arg DeleteTupleParams) error {
	_, err := db.Exec(ctx, deleteTuple,
		arg.ResourceType,
		arg.ResourceID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectPermission,
	)
	return err
}

const findTuples = `-- name: FindTuples :many
SELECT pk, resource_type, resource_id, relation, subject_type, subject_id, subject_permission FROM "tuple"
WHERE (resource_type = $1 OR $1 = '')
  AND (resource_id = $2 OR $2 = '')
  AND (relation = $3 OR $3 = '')
  AND (subject_type = $4 OR $4 = '')
  AND (subject_id = $5 OR $5 = '')
  AND (subject_permission = $6 OR $6 = '')
  AND pk > $7
ORDER BY pk ASC
LIMIT $8
`

type FindTuplesParams struct {
	ResourceType      string `db:"resource_type"`
	ResourceID        string `db:"resource_id"`
	Relation          string `db:"relation"`
	SubjectType       string `db:"subject_type"`
	SubjectID         string `db:"subject_id"`
	SubjectPermission string `db:"subject_permission"`
	LastPk            int64  `db:"last_pk"`
	LimitVal          int32  `db:"limit_val"`
}

// FindTuples
//
//	SELECT pk, resource_type, resource_id, relation, subject_type, subject_id, subject_permission FROM "tuple"
//	WHERE (resource_type = $1 OR $1 = '')
//	  AND (resource_id = $2 OR $2 = '')
//	  AND (relation = $3 OR $3 = '')
//	  AND (subject_type = $4 OR $4 = '')
//	  AND (subject_id = $5 OR $5 = '')
//	  AND (subject_permission = $6 OR $6 = '')
//	  AND pk > $7
//	ORDER BY pk ASC
//	LIMIT $8
func (q *Queries) FindTuples(ctx context.Context, db DBTX, arg FindTuplesParams) ([]Tuple, error) {
	rows, err := db.Query(ctx, findTuples,
		arg.ResourceType,
		arg.ResourceID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectPermission,
		arg.LastPk,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tuple
	for rows.Next() {
		var i Tuple
		if err := rows.Scan(
			&i.Pk,
			&i.ResourceType,
			&i.ResourceID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectPermission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTuplesByResourceBatch = `-- name: FindTuplesByResourceBatch :many
SELECT pk, resource_type, resource_id, relation, subject_type, subject_id, subject_permission FROM "tuple"
WHERE relation = $1
  AND resource_type = $2
  AND resource_id = ANY($3::text[])
`

type FindTuplesByResourceBatchParams struct {
	Relation     string   `db:"relation"`
	ResourceType string   `db:"resource_type"`
	ResourceIds  []string `db:"resource_ids"`
}

// FindTuplesByResourceBatch
//
//	SELECT pk, resource_type, resource_id, relation, subject_type, subject_id, subject_permission FROM "tuple"
//	WHERE relation = $1
//	  AND resource_type = $2
//	  AND resource_id = ANY($3::text[])
func (q *Queries) FindTuplesByResourceBatch(ctx context.Context, db DBTX, arg FindTuplesByResourceBatchParams) ([]Tuple, error) {
	rows, err := db.Query(ctx, findTuplesByResourceBatch, arg.Relation, arg.ResourceType, arg.ResourceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tuple
	for rows.Next() {
		var i Tuple
		if err := rows.Scan(
			&i.Pk,
			&i.ResourceType,
			&i.ResourceID,
			&i.Relation,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectPermission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTuple = `-- name: InsertTuple :one
INSERT INTO "tuple" (
  resource_type, resource_id, relation, subject_type, subject_id, subject_permission
) VALUES (
  $1, $2, $3, $4, $5, $6
)
ON CONFLICT (
  resource_type, resource_id, relation,
  subject_type, subject_id, subject_permission
) DO NOTHING
RETURNING pk
`

type InsertTupleParams struct {
	ResourceType      string `db:"resource_type"`
	ResourceID        string `db:"resource_id"`
	Relation          string `db:"relation"`
	SubjectType       string `db:"subject_type"`
	SubjectID         string `db:"subject_id"`
	SubjectPermission string `db:"subject_permission"`
}

// InsertTuple
//
//	INSERT INTO "tuple" (
//	  resource_type, resource_id, relation, subject_type, subject_id, subject_permission
//	) VALUES (
//	  $1, $2, $3, $4, $5, $6
//	)
//	ON CONFLICT (
//	  resource_type, resource_id, relation,
//	  subject_type, subject_id, subject_permission
//	) DO NOTHING
//	RETURNING pk
func (q *Queries) InsertTuple(ctx context.Context, db DBTX, arg InsertTupleParams) (int64, error) {
	row := db.QueryRow(ctx, insertTuple,
		arg.ResourceType,
		arg.ResourceID,
		arg.Relation,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectPermission,
	)
	var pk int64
	err := row.Scan(&pk)
	return pk, err
}
